#################################
#                               #
#    Oorlog Simulatie v1.7.5    #
#        door Xeterios          #
#                               #
#################################

# Gebruik /os reload om changes in de config.yml en maps.yml door te voeren
locale:
  prefix: "&x&f&5&3&8&3&8&lOorlog &8» &x&C&0&C&0&C&0"
  color: "&x&f&5&3&8&3&8"