name: OorlogSimulatie
version: '${project.version}'
main: mu.xeterios.oorlogsimulatie.Main
api-version: 1.16
authors: [ Xeterios ]
description: Een simulatie die een oorlog nabootst
depend: [WorldGuard]
commands:
  oorlogsimulatie:
    description: Control de oorlogsimulatie plugin
    usage: /<command>
    aliases: [os]
  leave:
    description: Leave de oorlogsimulatie
    usage: /<command>
  queue:
    description: Queue voor een oorlogsimulatie
    usage: /<command>